apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - deployment.yaml
  - httproute.yaml
  - pvc.yaml
  - service.yaml
  - external-secret.yaml
  - reference-grant.yaml
